import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-contract-manufacturing-yield-scrap-recovery",
  "engine": "recovery",
  "title": "Contract Manufacturing Yield & Scrap Recovery",
  "shortTitle": "Manufacturing Yield Recovery",
  "tagline": "Audit material consumption, yield, scrap, rework, labor, premiums, and contract manufacturer responsibility",
  "industry": "Contract Manufacturing Financial Assurance",
  "uiPort": 4587,
  "apiPort": 5587,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Unsupported conversion costs and supplier-responsible yield loss recovered with production evidence",
  "valueNarrative": "Reconcile manufacturing agreements, BOMs, routings, material issues, production orders, output, scrap, rework, labor, invoices, and credits.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedCost",
    "actualLabel": "Manufacturer Charged Amount",
    "expectedLabel": "Supported Manufacturing Cost",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "BOM, production, yield, scrap, labor, and commercial agreement evidence indicate recoverable contract manufacturing cost.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("manufacturing-agreement-library","MYR01","Manufacturing agreement library","Reconcile manufacturing agreement library using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed manufacturing agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Manufacturing agreement library Reference","text","MYR01-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("bom-and-routing-versioning","MYR02","BOM and routing versioning","Reconcile bom and routing versioning using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed bom and routing versioning decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","BOM and routing versioning Reference","text","MYR02-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("material-receipt-ingestion","MYR03","Material receipt ingestion","Reconcile material receipt ingestion using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed material receipt ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Material receipt ingestion Reference","text","MYR03-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("production-order-reconciliation","MYR04","Production-order reconciliation","Reconcile production-order reconciliation using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed production-order reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Production-order reconciliation Reference","text","MYR04-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("material-usage-variance","MYR05","Material usage variance","Reconcile material usage variance using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed material usage variance decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Material usage variance Reference","text","MYR05-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("yield-and-scrap-calculation","MYR06","Yield and scrap calculation","Reconcile yield and scrap calculation using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed yield and scrap calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Yield and scrap calculation Reference","text","MYR06-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("scrap-ownership-and-resale-credit","MYR07","Scrap ownership and resale credit","Reconcile scrap ownership and resale credit using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed scrap ownership and resale credit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Scrap ownership and resale credit Reference","text","MYR07-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("rework-responsibility-analysis","MYR08","Rework responsibility analysis","Reconcile rework responsibility analysis using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed rework responsibility analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Rework responsibility analysis Reference","text","MYR08-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("labor-and-conversion-cost-validation","MYR09","Labor and conversion-cost validation","Reconcile labor and conversion-cost validation using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed labor and conversion-cost validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Labor and conversion-cost validation Reference","text","MYR09-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("overtime-and-premium-audit","MYR10","Overtime and premium audit","Reconcile overtime and premium audit using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed overtime and premium audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Overtime and premium audit Reference","text","MYR10-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("material-substitution-control","MYR11","Material substitution control","Reconcile material substitution control using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed material substitution control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Material substitution control Reference","text","MYR11-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("quality-rejection-chargeback","MYR12","Quality rejection chargeback","Reconcile quality rejection chargeback using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed quality rejection chargeback decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Quality rejection chargeback Reference","text","MYR12-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("finished-goods-reconciliation","MYR13","Finished-goods reconciliation","Reconcile finished-goods reconciliation using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed finished-goods reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Finished-goods reconciliation Reference","text","MYR13-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("supplier-recovery-package","MYR14","Supplier recovery package","Reconcile supplier recovery package using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed supplier recovery package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Supplier recovery package Reference","text","MYR14-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("debit-and-credit-reconciliation","MYR15","Debit and credit reconciliation","Reconcile debit and credit reconciliation using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed debit and credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Debit and credit reconciliation Reference","text","MYR15-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]}),
feature("site-product-and-supplier-analytics","MYR16","Site product and supplier analytics","Reconcile site product and supplier analytics using manufacturing agreements, BOMs, routings, purchase and consigned materials, production orders, output, scrap, rework, labor, overtime, quality rejects, invoices, and credits.","Produce a governed site product and supplier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturerProduct","Contract Manufacturer / Product","text","Atlas Manufacturing / PROD-8841"],["caseReference","Site product and supplier analytics Reference","text","MYR16-2026-001"],["chargedAmount","Manufacturer Charged Amount","currency",2840000],["supportedCost","Supported Manufacturing Cost","currency",2515000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Electronics assembly","Consumer product production","Medical device contract line","Automotive component program","Industrial equipment assembly"]})
]);
